[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mesarpg"
version = "0.1.0"
description = "MesaRPG tabletop server"
authors = [ { name = "DAMSanti" } ]
readme = "README.md"
requires-python = ">=3.10"
